### ISSUE TITLE
HPNA Response Code 221 creates an exception 

### ISSUE THREAD

**Issue by AkosC-FDC** [spenceation/hpnapy#14]
I run into a situation that by calling show_task with a specific task ID, like show_task(id="1234'), HP NA responded with status code 221 and with all details of my query.  However this caused an exception in python. 

I believe that return code 221 should be  in the list at line 1056 in hpnapy.py

**Comment by spenceation** [comment]
Hi @AkosC-FDC ,

Could you please provide the exception returned in python?

**Comment by AkosC-FDC** [comment]
Hi @spenceation, 

here is the output:

C:\Users\FBL49SA\PycharmProjects\CryptoMAP_parser\venv\Scripts\python.exe C:/Users/FBL49SA/.PyCharmCE2018.3/config/scratches/hpnapy_test.py
Traceback (most recent call last):
  File "C:/Users/FBL49SA/.PyCharmCE2018.3/config/scratches/hpnapy_test.py", line 11, in <module>
    task_result=hpna.show_task(id=task.scheduleTaskID)
  File "C:\Users\FBL49SA\PycharmProjects\CryptoMAP_parser\venv\lib\site-packages\hpnapy\hpnapy.py", line 893, in show_task
    return self._connector.execute_single_result_call("show_task", **kwargs)
  File "C:\Users\FBL49SA\PycharmProjects\CryptoMAP_parser\venv\lib\site-packages\hpnapy\hpnapy.py", line 1092, in execute_single_result_call
    api_response = self._get_api_query_response(command_to_call, **kwargs)
  File "C:\Users\FBL49SA\PycharmProjects\CryptoMAP_parser\venv\lib\site-packages\hpnapy\hpnapy.py", line 1088, in _get_api_query_response
    self._validate_api_response(api_response)
  File "C:\Users\FBL49SA\PycharmProjects\CryptoMAP_parser\venv\lib\site-packages\hpnapy\hpnapy.py", line 1061, in _validate_api_response
    api_response.Status, api_response.Text))
hpnapy.exceptions.HPNAQueryError: HP NA API Execution error: Status:221, Text:None

Process finished with exit code 1

**Comment by spenceation** [comment]
Added 221 as a response code in 1.0.6. #
